# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-9b92a2ea-8f3e-4c02-8091-ecc81a3a8d49";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-9b92a2ea-8f3e-4c02-8091-ecc81a3a8d49".device =
    "/dev/disk/by-uuid/9b92a2ea-8f3e-4c02-8091-ecc81a3a8d49";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CC12-0700";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-71936e47-c47f-47e7-8c39-c942ace26eb1"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
