words = [
    "DDC",
    "Gpu",
    "Nouveau",
    "Xorg",
    "adwaita",
    "alacritty",
    "alsa",
    "antonk",
    "appimage",
    "aseprite",
    "binfmt",
    "brightnessctl",
    "btop",
    "chezmoi",
    "clippy",
    "cssmodules",
    "ddcci",
    "ddcci's",
    "drun",
    "efi",
    "efm",
    "esac",
    "finegrained",
    "fnott",
    "fontconfig",
    "freedesktop",
    "fwupd",
    "fzf",
    "gamemode",
    "gammastep",
    "gdm",
    "geary",
    "ghostty",
    "golangci",
    "gopls",
    "inotify",
    "ints",
    "kanshi",
    "kanshictl",
    "langserver",
    "libnotify",
    "mitchellh",
    "modesetting",
    "neovim",
    "networkmanager",
    "nixd",
    "nixfmt",
    "nixos",
    "nixpkgs",
    "nvidia",
    "nvim",
    "oneshot",
    "openvpn",
    "optionals",
    "pamixer",
    "passthru",
    "patrickswijgman",
    "pipewire",
    "pkgs",
    "playerctl",
    "plotkaraphael",
    "pname",
    "pomodoro",
    "prettierd",
    "pulseaudio",
    "ripgrep",
    "rtkit",
    "rustfmt",
    "screencast",
    "statusline",
    "stdenv",
    "stylua",
    "swaybg",
    "swayidle",
    "swayline",
    "swaylock",
    "swayopacity",
    "swijgman",
    "taplo",
    "tofi",
    "venv",
    "virtualisation",
    "vscode",
    "vtsls",
    "wget",
    "wlopm",
    "wlr",
    "wlroots",
    "xdg",
    "xkb",
    "xwayland",
    "yaru",
]
