words = [
  "adwaita",
  "alacritty",
  "alsa",
  "antonk",
  "appimage",
  "aseprite",
  "astro",
  "augroup",
  "autocmds",
  "autoindent",
  "autopairs",
  "autotrigger",
  "binfmt",
  "bing",
  "birb",
  "bitwarden",
  "breakindent",
  "brightnessctl",
  "btop",
  "bufnr",
  "chezmoi",
  "cjs",
  "clippy",
  "completeopt",
  "crypto",
  "cssls",
  "cssmodules",
  "cursorline",
  "dbus",
  "dconf",
  "ddc",
  "ddcci",
  "ddcci's",
  "drun",
  "efi",
  "efm",
  "esac",
  "esc",
  "expandtab",
  "finegrained",
  "fnott",
  "fontconfig",
  "freedesktop",
  "fwupd",
  "fzf",
  "gamemode",
  "gammastep",
  "gdm",
  "geary",
  "ghostty",
  "gitcommit",
  "gofmt",
  "golangci",
  "gopls",
  "gpu",
  "grd",
  "gre",
  "gri",
  "grr",
  "grt",
  "gvariant",
  "hlsearch",
  "ignorecase",
  "inccommand",
  "incsearch",
  "inotify",
  "ints",
  "jit",
  "jsonls",
  "kanshi",
  "kanshictl",
  "keybind",
  "keymaps",
  "keyutils",
  "langserver",
  "libnotify",
  "librewolf",
  "lspconfig",
  "luks",
  "mapleader",
  "maplocalleader",
  "menuone",
  "mitchellh",
  "modesetting",
  "nargs",
  "neovim",
  "netrw",
  "networkmanager",
  "nixd",
  "nixfmt",
  "nixos",
  "nixpkgs",
  "nixvim",
  "nohl",
  "nop",
  "noselect",
  "nouveau",
  "nvidia",
  "nvim",
  "oneshot",
  "openvpn",
  "optionals",
  "pamixer",
  "passthru",
  "patrickswijgman",
  "pipewire",
  "pkgs",
  "playerctl",
  "plotkaraphael",
  "pname",
  "pnpm",
  "pomodoro",
  "prettierd",
  "pulseaudio",
  "pumborder",
  "pylsp",
  "qutebrowser",
  "relativenumber",
  "ripgrep",
  "rtkit",
  "rustfmt",
  "screencast",
  "scrolloff",
  "shiftwidth",
  "showbreak",
  "showmatch",
  "signcolumn",
  "smartcase",
  "softtabstop",
  "splitbelow",
  "splitright",
  "spotify",
  "statusline",
  "stdenv",
  "stylelint",
  "stylelintrc",
  "stylua",
  "subword",
  "swapfile",
  "swaybg",
  "swayidle",
  "swayline",
  "swaylock",
  "swayopacity",
  "swijgman",
  "tabstop",
  "taplo",
  "textobject",
  "textobjects",
  "timeoutlen",
  "tofi",
  "undofile",
  "updatetime",
  "userscript",
  "venv",
  "vimgrep",
  "virtualisation",
  "vscode",
  "vtsls",
  "wearespindle",
  "wget",
  "winborder",
  "wlopm",
  "wlr",
  "wlroots",
  "xdg",
  "xkb",
  "xorg",
  "xwayland",
  "yamlls",
  "yaru",
]
